const fs = require('fs');

// We will generate 20 realistic, high-quality intermediate words for each letter A-Z
// with accurate English definitions, Tamil translations, contexts, synonyms, and antonyms.

const alphabetWords = {
  A: [
    { id: "adaptable", word: "Adaptable", pos: "adj", def: "Able to adjust to new conditions.", tamil: "மாற்றங்களுக்கு ஏற்ப தகவமைத்துக் கொள்ளக்கூடிய.", lit: "She proved adaptable in the face of sudden crisis.", litTa: "திடீர் நெருக்கடியைச் சமாளிக்க அவளால் தகவமைத்துக்கொள்ள முடிந்தது.", form: "An adaptable team is essential for modern enterprise growth.", formTa: "நவீன நிறுவன வளர்ச்சிக்கு தகவமைத்துக் கொள்ளக்கூடிய குழு அவசியம்.", syn: ["flexible", "versatile"], ant: ["rigid"] },
    { id: "ambitious", word: "Ambitious", pos: "adj", def: "Having or showing a strong desire and determination to succeed.", tamil: "உயர் லட்சியம் கொண்ட / வைராக்கியமான.", lit: "His ambitious project aimed to revitalize the entire community.", litTa: "அவரது லட்சியத் திட்டம் முழு சமூகத்தையும் புதுப்பிப்பதை நோக்கமாகக் கொண்டிருந்தது.", form: "We have set ambitious targets for this quarter.", formTa: "இந்தக் காலாண்டிற்கு நாங்கள் உயரிய இலக்குகளை நிர்ணயித்தಿದ್ದೇವೆ.", syn: ["driven", "aspiring"], ant: ["lazy", "unambitious"] },
    { id: "amiable", word: "Amiable", pos: "adj", def: "Having or displaying a friendly and pleasant manner.", tamil: "நட்பான மற்றும் கனிவான.", lit: "The host welcomed every guest with an amiable smile.", litTa: "விருந்தினர் அனைவரையும் அன்பான புன்னகையுடன் வரவேற்றார்.", form: "Her amiable disposition made her a favorite among colleagues.", formTa: "அவளது நட்புணர்வு சக ஊழியர்களிடையே அவளைப் பிடித்தமானவளாக மாற்றியது.", syn: ["friendly", "cordial"], ant: ["hostile", "unfriendly"] },
    { id: "allocate", word: "Allocate", pos: "verb", def: "Distribute (resources or duties) for a particular purpose.", tamil: "ஒதுக்கீடு செய்தல்.", lit: "The committee decided to allocate funds for library renovation.", litTa: "நூலக சீரமைப்பிற்கு நிதி ஒதுக்கீடு செய்ய குழு முடிவு செய்தது.", form: "We must allocate sufficient time for project review.", formTa: "திட்ட மதிப்பீட்டிற்கு போதுமான நேரத்தை நாம் ஒதுக்க வேண்டும்.", syn: ["assign", "distribute"], ant: ["retain"] },
    { id: "authentic", word: "Authentic", pos: "adj", def: "Of undisputed origin; genuine.", tamil: "உண்மையான / அசல்.", lit: "Historians confirmed that the ancient manuscript was authentic.", litTa: "அந்தப் பழங்கால கையெழுத்துப் பிரதி உண்மையானது என்பதை வரலாற்றாசிரியர்கள் உறுதிப்படுத்தினர்.", form: "We need authentic feedback from our users.", formTa: "எங்கள் பயனர்களிடமிருந்து உண்மையான கருத்துகள் எங்களுக்குத் தேவை.", syn: ["genuine", "real"], ant: ["fake", "counterfeit"] },
    { id: "advocate", word: "Advocate", pos: "noun", def: "A person who publicly supports or recommends a particular cause or policy.", tamil: "ஆதரவாளர் / வக்கீல்.", lit: "She became a passionate advocate for environmental protection.", litTa: "அவள் சுற்றுச்சூழல் பாதுகாப்பின் தீவிர ஆதரவாளரானாள்.", form: "He is a strong advocate of transparent governance.", formTa: "அவர் வெளிப்படையான நிர்வாகத்தின் தீவிர ஆதரவாளர்.", syn: ["supporter", "champion"], ant: ["opponent", "critic"] },
    { id: "abundance", word: "Abundance", pos: "noun", def: "A very large quantity of something.", tamil: "மிகுதி / செழிப்பு.", lit: "The fertile valley yielded an abundance of crops.", litTa: "வளமான பள்ளத்தாக்கு ஏராளமான பயிர்களை விளைவித்தது.", form: "There is an abundance of evidence supporting this theory.", formTa: "இந்தக் கோட்பாட்டை ஆதரிக்க ஏராளமான சான்றுகள் உள்ளன.", syn: ["plenty", "wealth"], ant: ["scarcity", "poverty"] },
    { id: "appease", word: "Appease", pos: "verb", def: "Pacify or placate (someone) by acceding to their demands.", tamil: "சமாதானப்படுத்துதல் / சாந்தப்படுத்துதல்.", lit: "The leader tried to appease the restless crowd with promises of reform.", litTa: "சீர்திருத்த வாக்குறுதிகளால் அமைதியற்ற கூட்டத்தைச் சமாதானப்படுத்தத் தலைவர் முயன்றார்.", form: "Management sought to appease the unions through negotiation.", formTa: "பேச்சுவார்த்தை மூலம் தொழிற்சங்கங்களைச் சமாதானப்படுத்த நிர்வாகம் முயன்றது.", syn: ["pacify", "placate"], ant: ["provoke", "agitate"] },
    { id: "astute", word: "Astute", pos: "adj", def: "Having or showing an ability to accurately assess situations or people and turn this to one's advantage.", tamil: "நுண்ணறிவுள்ள / விவேகமான.", lit: "An astute investor knows when to buy and when to sell.", litTa: "ஒரு விவேகமான முதலீட்டாளருக்கு எப்போது வாங்க வேண்டும், எப்போது விற்க வேண்டும் என்று தெரியும்.", form: "Her astute observations helped resolve the deadlock.", formTa: "அவளது விவேகமான அவதானிப்புகள் முட்டுக்கட்டையைத் தீர்க்க உதவின.", syn: ["shrewd", "clever"], ant: ["foolish", "naive"] },
    { id: "audacious", word: "Audacious", pos: "adj", def: "Showing a willingness to take surprisingly bold risks.", tamil: "துணிச்சலான / சாகசமான.", lit: "The climbers made an audacious attempt to scale the northern ridge.", litTa: "மலையேறுபவர்கள் வடக்குப் பாறையை ஏறும் துணிச்சலான முயற்சியை மேற்கொண்டனர்.", form: "The startup proposed an audacious plan to transform urban transit.", formTa: "நகரப் போக்குவரத்தை மாற்றியமைக்க அந்த ஸ்டார்ட்அப் ஒரு துணிச்சலான திட்டத்தை முன்மொழிந்தது.", syn: ["bold", "daring"], ant: ["timid", "cautious"] },
    { id: "anomaly", word: "Anomaly", pos: "noun", def: "Something that deviates from what is standard, normal, or expected.", tamil: "விதிவிலக்கு / முரண்பாடு.", lit: "Scientists investigated the sudden atmospheric anomaly.", litTa: "விஞ்ஞானிகள் திடீர் வளிமண்டல முரண்பாட்டை விசாரித்தனர்.", form: "This data point is an anomaly and should be rechecked.", formTa: "இந்தத் தரவுப் புள்ளி ஒரு முரண்பாடாகும், அதை மீண்டும் சரிபார்க்க வேண்டும்.", syn: ["irregularity", "deviation"], ant: ["normality", "regularity"] },
    { id: "alleviate", word: "Alleviate", pos: "verb", def: "Make (suffering, deficiency, or a problem) less severe.", tamil: "குறைத்தல் / தணித்தல்.", lit: "Medicines were distributed to alleviate the pain of the victims.", litTa: "பாதிக்கப்பட்டவர்களின் வலியைத் தணிக்க மருந்துகள் வழங்கப்பட்டன.", form: "New policies were introduced to alleviate poverty.", formTa: "வறுமையைக் குறைக்க புதிய கொள்கைகள் அறிமுகப்படுத்தப்பட்டன.", syn: ["reduce", "ease"], ant: ["intensify", "worsen"] },
    { id: "aesthetic", word: "Aesthetic", pos: "adj", def: "Concerned with beauty or the appreciation of beauty.", tamil: "அழகுியல் தொடர்பான.", lit: "The temple is renowned for its high aesthetic value.", litTa: "கோவில் அதன் உயர் அழகுியல் மதிப்புக்காகப் புகழ்பெற்றது.", form: "We focused on improving the aesthetic appeal of the interface.", formTa: "இடைமுகத்தின் அழகுியல் ஈர்ப்பை மேம்படுத்துவதில் நாங்கள் கவனம் செலுத்தினோம்.", syn: ["artistic", "visual"], ant: ["plain", "ugly"] },
    { id: "aspire", word: "Aspire", pos: "verb", def: "Direct one's hopes or ambitions towards achieving something.", tamil: "இலட்சியமாகக் கொள்ளுதல் / பெருமிதம் கொள்ளுதல்.", lit: "Every student should aspire to achieve excellence in learning.", litTa: "ஒவ்வொரு மாணவரும் கற்றலில் சிறந்து விளங்க இலட்சியம் கொள்ள வேண்டும்.", form: "We aspire to build a sustainable future.", formTa: "நாங்கள் நிலையான எதிர்காலத்தை உருவாக்க விரும்புகிறோம்.", syn: ["strive", "aim"], ant: ["despair"] },
    { id: "assert", word: "Assert", pos: "verb", def: "State a fact or belief confidently and forcefully.", tamil: "உறுதியாகக் கூறுதல்.", lit: "She chose to assert her independence in every decision.", litTa: "அவள் ஒவ்வொரு முடிவிலும் தனது சுதந்திரத்தை உறுதியாக நிலைநாட்டத் தேர்ந்தெடுத்தாள்.", form: "The speaker proceeded to assert the importance of education.", formTa: "பேச்சாளர் கல்வியின் முக்கியத்துவத்தை உறுதியாகக் கூறினார்.", syn: ["declare", "maintain"], ant: ["deny", "renounce"] },
    { id: "anonymous", word: "Anonymous", pos: "adj", def: "Not identified by name; of unknown name.", tamil: "அடையாளம் தெரியாத / பெயர் குறிப்பிடப்படாத.", lit: "An anonymous donor contributed generously to the charity.", litTa: "அடையாளம் தெரியாத நன்கொடையாளர் தொண்டு நிறுவனத்திற்குத் தாராளமாக உதவினார்.", form: "Users can submit feedback through an anonymous survey.", formTa: "பயனர்கள் பெயர் குறிப்பிடப்படாத கணக்கெடுப்பு மூலம் கருத்துக்களை சமர்ப்பிக்கலாம்.", syn: ["unnamed", "unknown"], ant: ["named", "identified"] },
    { id: "articulate", word: "Articulate", pos: "adj", def: "Having or showing the ability to speak fluently and coherently.", tamil: "தெளிவாகப் பேசக்கூடிய.", lit: "The young scholar gave an articulate presentation.", litTa: "இளம் அறிஞர் தெளிவாக விளக்கமளித்தார்.", form: "An articulate communicator inspires trust.", formTa: "தெளிவாகத் தொடர்புகொள்பவர் நம்பிக்கையை ஊட்டுவார்.", syn: ["eloquent", "fluent"], ant: ["inarticulate", "mumbling"] },
    { id: "altruistic", word: "Altruistic", pos: "adj", def: "Showing a disinterested and selfless concern for the well-being of others.", tamil: "மற்றவர் நலன் பேணும் / சுயநலமற்ற.", lit: "Her altruistic acts of kindness touched many lives.", litTa: "அவளது சுயநலமற்ற கருணைக் செயல்கள் பலரது வாழ்வைத் தொட்டன.", form: "Philanthropy is driven by altruistic motives.", formTa: "தொண்டு நிறுவனங்கள் சுயநலமற்ற நோக்கங்களால் இயக்கப்படுகின்றன.", syn: ["selfless", "charitable"], ant: ["selfish", "egoistic"] },
    { id: "augment", word: "Augment", pos: "verb", def: "Make (something) greater by adding to it; increase.", tamil: "பெருக்குதல் / கூட்டுதல்.", lit: "He sought to augment his income by working part-time.", litTa: "பகுதிநேரமாக வேலை செய்து தனது வருமானத்தை உயர்த்த முயன்றார்.", form: "Data analytics help augment strategic planning.", formTa: "தரவுப் பகுப்பாய்வு மூலோபாய திட்டமிடலை மேம்படுத்த உதவுகிறது.", syn: ["increase", "expand"], ant: ["decrease", "reduce"] },
    { id: "authentic", word: "Authentic", pos: "adj", def: "Of undisputed origin; genuine.", tamil: "உண்மையான.", lit: "The artwork was verified as authentic.", litTa: "கலைப்படைப்பு உண்மையானது என சரிபார்க்கப்பட்டது.", form: "Ensure your login credentials are authentic.", formTa: "உங்கள் உள்நுழைவு சான்றுகள் உண்மையானவை என்பதை உறுதிப்படுத்தவும்.", syn: ["genuine", "real"], ant: ["fake"] }
  ]
};

// Let's generate entries for B through Z programmatically or with varied words so each has 20 robust words.
// To ensure 20 words for each letter B..Z, let's write a generator function or table.
console.log("Ready");
