import os, json, re

# Python merger for all A to Z lexicon updates

LEXICON_ADDITIONS = {
    # E
    "e": [
        {"id": "eccentric", "word": "Eccentric", "partOfSpeech": "adj.", "difficulty": "Moderate", "tags": ["Arts & Culture", "Literature"],
         "englishDefinition": "Unconventional and slightly strange in behavior or appearance.", "tamilDefinition": "விசித்திரமான அல்லது இயல்பு மாறிய.",
         "literaryContext": {"english": "The eccentric inventor spent decades crafting intricate brass clocks.", "tamil": "விசித்திரமான கண்டுபிடிப்பாளர் பித்தளைக் கடிகாரங்களை உருவாக்குவதில் பல தசாப்தங்களைச் செலவிட்டார்.", "sourceNote": "Gothic Novel"},
         "formalSpeechContext": {"english": "While his research methods were eccentric, his scientific findings proved remarkably accurate.", "tamil": "அவரது ஆராய்ச்சி முறைகள் விசித்திரமானவையாக இருந்தாலும், அவரது அறிவியல் கண்டுபிடிப்புகள் வியக்கத்தக்க வகையில் துல்லியமாக இருந்தன.", "sourceNote": "Academic Lecture"},
         "synonyms": ["unconventional", "quirky", "peculiar", "odd"], "antonyms": ["conventional", "ordinary", "normal", "typical"]},
        {"id": "elusive", "word": "Elusive", "partOfSpeech": "adj.", "difficulty": "Advanced", "tags": ["Literature", "Philosophy"],
         "englishDefinition": "Difficult to find, catch, or achieve; difficult to remember.", "tamilDefinition": "எளிதில் புரிந்துகொள்ள முடியாத அல்லது பிடிபடாத.",
         "literaryContext": {"english": "Truth remained an elusive goal for the philosopher searching through ancient texts.", "tamil": "பண்டைய நூல்களை ஆராய்ந்த தத்துவஞானிக்கு உண்மை என்பது பிடிபடாத இலக்காகவே இருந்தது.", "sourceNote": "Philosophical Essay"},
         "formalSpeechContext": {"english": "A permanent diplomatic consensus remains elusive despite months of high-level negotiations.", "tamil": "மாதக்கணக்கில் உயர்மட்டப் பேச்சுவார்த்தைகள் நடந்தபோதிலும் நிரந்தர இராஜதந்திர உடன்பாடு பிடிபடாததாகவே உள்ளது.", "sourceNote": "Foreign Policy Review"},
         "synonyms": ["evasive", "slippery", "subtle", "indefinite"], "antonyms": ["accessible", "tangible", "clear", "definite"]},
        {"id": "embrace", "word": "Embrace", "partOfSpeech": "verb", "difficulty": "Moderate", "tags": ["Literature", "Ethics & Society"],
         "englishDefinition": "Hold closely in one's arms; accept or support a belief enthusiastically.", "tamilDefinition": "தழுவுதல் அல்லது மகிழ்வோடு ஏற்றுக்கொள்ளுதல்.",
         "literaryContext": {"english": "The long-separated brothers wept and stepped forward to embrace.", "tamil": "வெகுநாட்களாகப் பிரிந்திருந்த சகோதரர்கள் அழுது முன்னோக்கி வந்து கட்டியணைத்துத் தழுவினர்.", "sourceNote": "Epic Tale"},
         "formalSpeechContext": {"english": "Organizations must embrace digital transformation to remain competitive in global markets.", "tamil": "உலகளாவிய சந்தைகளில் போட்டியிடுவதற்காக நிறுவனங்கள் டிஜிட்டல் மாற்றத்தை மகிழ்வோடு ஏற்றுக்கொள்ள வேண்டும்.", "sourceNote": "Business Strategy Address"},
         "synonyms": ["adopt", "welcome", "clasp", "enfold"], "antonyms": ["reject", "spurn", "exclude", "shun"]},
        {"id": "emulate", "word": "Emulate", "partOfSpeech": "verb", "difficulty": "Advanced", "tags": ["Ethics & Society", "Literature"],
         "englishDefinition": "Match or surpass a person or achievement, typically by imitation.", "tamilDefinition": "பின்பற்றுதல் அல்லது நிகராக செயல்படுதல்.",
         "literaryContext": {"english": "Young poets sought to emulate the majestic meter of classical Tamil epic verse.", "tamil": "இளம் கவிஞர்கள் செம்மொழித் தமிழ் காப்பியச் செய்யுளின் கம்பீரமான சந்தத்தைப் பின்பற்ற விரும்பினர்.", "sourceNote": "Poetic Theory"},
         "formalSpeechContext": {"english": "Developing nations aspire to emulate successful sustainable urban models.", "tamil": "வளரும் நாடுகள் வெற்றிகரமான நிலையான நகர்ப்புற மாதிரிகளைப் பின்பற்ற விரும்புகின்றன.", "sourceNote": "Urban Development Forum"},
         "synonyms": ["imitate", "copy", "mirror", "replicate"], "antonyms": ["neglect", "ignore", "abandon", "shun"]},
        {"id": "endorse", "word": "Endorse", "partOfSpeech": "verb", "difficulty": "Moderate", "tags": ["Politics", "Formal Speech"],
         "englishDefinition": "Declare one's public approval or support of.", "tamilDefinition": "ஒப்புதல் கொடுத்தல் அல்லது ஆதரித்தல்.",
         "literaryContext": {"english": "The respected scholar chose to endorse the groundbreaking historical thesis.", "tamil": "மதிப்பிற்குரிய அறிஞர் அந்த விசித்திரமான வரலாற்று ஆய்வுக் கட்டுரையை ஆதரிக்கத் தேர்ந்தெடுத்தார்.", "sourceNote": "Academic Review"},
         "formalSpeechContext": {"english": "The committee voted unanimously to endorse the proposed public health campaign.", "tamil": "முன்மொழியப்பட்ட பொது சுகாதாரப் பிரச்சாரத்திற்கு ஒப்புதல் அளிக்க குழு ஏகோபித்து வாக்களித்தது.", "sourceNote": "Health Board Report"},
         "synonyms": ["support", "sanction", "approve", "back"], "antonyms": ["oppose", "reject", "disapprove", "condemn"]},
        {"id": "endow", "word": "Endow", "partOfSpeech": "verb", "difficulty": "Advanced", "tags": ["Formal Speech", "Arts & Culture"],
         "englishDefinition": "Provide with a quality, ability, or asset; give income or property.", "tamilDefinition": "கொடை கொடுத்தல் அல்லது வழங்குதல்.",
         "literaryContext": {"english": "Nature endowed the fertile valley with abundant fresh springs and flora.", "tamil": "இயற்கை அந்த வளமான பள்ளத்தாக்கிற்கு ஏராளமான நன்னீர் ஊற்றுகளையும் தாவரங்களையும் கொடையாக வழங்கியது.", "sourceNote": "Nature Prose"},
         "formalSpeechContext": {"english": "Philanthropists agreed to endow a new university chair in Tamil classical literature.", "tamil": "செம்மொழித் தமிழ் இலக்கியத்தில் ஒரு புதிய பல்கலைக்கழகப் பீடத்திற்கு கொடை வழங்கக் கொடையாளர்கள் ஒப்புக்கொண்டனர்.", "sourceNote": "University Endowment Speech"},
         "synonyms": ["bestow", "provide", "furnish", "equip"], "antonyms": ["deprive", "strip", "divest", "withhold"]},
        {"id": "ensnared", "word": "Ensnared", "partOfSpeech": "adj.", "difficulty": "Advanced", "tags": ["Literature", "Ethics & Society"],
         "englishDefinition": "Caught in or as if in a trap or snare.", "tamilDefinition": "சிக்கிய அல்லது கண்ணியில் அகப்பட்ட.",
         "literaryContext": {"english": "The unsuspecting prince found himself ensnared in a web of courtly deception.", "tamil": "அறியாத இளவரசன் அரசவை ஏமாற்று வலைக்குள் கண்ணியில் அகப்பட்டுக்கொண்டான்.", "sourceNote": "Historical Fiction"},
         "formalSpeechContext": {"english": "Unwary investors were ensnared by fraudulent offshore financial schemes.", "tamil": "எச்சரிக்கையற்ற முதலீட்டாளர்கள் மோசடியான வெளிநாட்டு நிதித் திட்டங்களில் சிக்கினர்.", "sourceNote": "Financial Regulation Report"},
         "synonyms": ["trapped", "entangled", "captured", "enmeshed"], "antonyms": ["freed", "released", "liberated", "extricated"]},
        {"id": "enunciate", "word": "Enunciate", "partOfSpeech": "verb", "difficulty": "Advanced", "tags": ["Formal Speech", "Poetics & Rhetoric"],
         "englishDefinition": "Say or pronounce clearly; express an idea in clear terms.", "tamilDefinition": "தெளிவாகக் கூறுதல் அல்லது உச்சரித்தல்.",
         "literaryContext": {"english": "The orator took care to enunciate every syllable so the vast crowd could hear.", "tamil": "திரண்டிருந்த பெருந்திரள் மக்கள் கேட்கும் பொருட்டு பேச்சாளர் ஒவ்வொரு அசையையும் தெளிவாக உச்சரிக்கக் கவனமெடுத்தார்.", "sourceNote": "Rhetorical Criticism"},
         "formalSpeechContext": {"english": "Policy leaders must clearly enunciate our long-term objectives to stakeholders.", "tamil": "கொள்கைத் தலைவர்கள் பங்குதாரர்களுக்கு நமது நீண்டகால இலக்குகளைத் தெளிவாகக் கூற வேண்டும்.", "sourceNote": "Corporate Assembly"},
         "synonyms": ["articulate", "pronounce", "express", "state"], "antonyms": ["mumble", "slur", "garble", "muffle"]},
        {"id": "ephemeral", "word": "Ephemeral", "partOfSpeech": "adj.", "difficulty": "Literary", "tags": ["Philosophy", "Literature"],
         "englishDefinition": "Lasting for a very short time; fleeting.", "tamilDefinition": "குறுகிய கால அல்லது தற்காலிக.",
         "literaryContext": {"english": "Poets frequently reflect upon the ephemeral nature of worldly fame and beauty.", "tamil": "உலகப் புகழும் அழகும் தற்காலிகமானவை என்ற இயல்பு குறித்துக் கவிஞர்கள் அடிக்கடி சிந்திக்கிறார்கள்.", "sourceNote": "Philosophical Verse"},
         "formalSpeechContext": {"english": "Market spikes caused by rumors are ephemeral and rarely sustain economic growth.", "tamil": "வதந்திகளால் ஏற்படும் சந்தை உயர்ர்வுகள் தற்காலிகமானவை, அவை அரிதாகவே பொருளாதார வளர்ச்சியைத் தக்கவைக்கின்றன.", "sourceNote": "Financial Analysis"},
         "synonyms": ["transient", "fleeting", "momentary", "evanescent"], "antonyms": ["permanent", "enduring", "lasting", "perpetual"]},
        {"id": "erratic", "word": "Erratic", "partOfSpeech": "adj.", "difficulty": "Moderate", "tags": ["Science", "Ethics & Society"],
         "englishDefinition": "Not even or regular in pattern or movement; unpredictable.", "tamilDefinition": "ஒழுங்கற்ற அல்லது சீரற்ற.",
         "literaryContext": {"english": "The vessel drifted helplessly under the erratic winds of the monsoonal storm.", "tamil": "பருவமழைக் புயலின் ஒழுங்கற்ற காற்றினால் கப்பல் திக்கற்று மிதந்தது.", "sourceNote": "Maritime Novel"},
         "formalSpeechContext": {"english": "Erratic market fluctuations require central banks to implement stabilizing measures.", "tamil": "சீரற்ற சந்தை ஏற்ற இறக்கங்கள் மத்திய வங்கிகள் ஸ்திரப்படுத்தும் நடவடிக்கைகளை அமல்படுத்தத் தேவைப்படுத்துகின்றன.", "sourceNote": "Economic Briefing"},
         "synonyms": ["unpredictable", "inconsistent", "irregular", "variable"], "antonyms": ["predictable", "consistent", "steady", "regular"]},
        {"id": "essentially", "word": "Essentially", "partOfSpeech": "adv.", "difficulty": "Moderate", "tags": ["Formal Speech", "Philosophy"],
         "englishDefinition": "In a fundamental or basic way; intrinsically.", "tamilDefinition": "அடிப்படையில் அல்லது முக்கியமாக.",
         "literaryContext": {"english": "Though written centuries apart, the two poems are essentially expressing the same grief.", "tamil": "நூற்றாண்டுகள் இடைவெளியில் எழுதப்பட்ட போதிலும், இரண்டு கவிதைகளும் அடிப்படையில் ஒரே துயரத்தையே வெளிப்படுத்துகின்றன.", "sourceNote": "Literary Comparison"},
         "formalSpeechContext": {"english": "The new agreement is essentially an extension of existing commercial treaties.", "tamil": "புதிய ஒப்பந்தம் அடிப்படையில் இருக்கும் வர்த்தக உடன்படிக்கைகளின் நீட்டிப்பாகும்.", "sourceNote": "Trade Policy Conference"},
         "synonyms": ["fundamentally", "basically", "primarily", "intrinsically"], "antonyms": ["superficially", "secondarily", "incidentally"]},
        {"id": "ethos", "word": "Ethos", "partOfSpeech": "noun", "difficulty": "Advanced", "tags": ["Philosophy", "Ethics & Society"],
         "englishDefinition": "The characteristic spirit of a culture, era, or community as manifested in its beliefs and aspirations.", "tamilDefinition": "நெறிமுறைகள் அல்லது பண்பாட்டு இயல்பு.",
         "literaryContext": {"english": "Ancient Tamil Sangam poetry reflects a profound ethos of honor, courage, and hospitality.", "tamil": "பண்டைய தமிழ் சங்கக் கவிதைகள் மானம், வீரம், விருந்தோம்பல் ஆகிய ஆழமான நெறிமுறைகளைப் பிரதிபலிக்கின்றன.", "sourceNote": "Cultural Hermeneutics"},
         "formalSpeechContext": {"english": "Our corporate ethos prioritizes environmental stewardship alongside profitability.", "tamil": "எங்கள் நிறுவன நெறிமுறை லாபத்தோடு சேர்ந்து சுற்றுச்சூழல் பாதுகாப்பிற்கும் முன்னுரிமை அளிக்கிறது.", "sourceNote": "Corporate Governance Report"},
         "synonyms": ["character", "spirit", "morals", "code", "tenets"], "antonyms": []},
        {"id": "exorbitant", "word": "Exorbitant", "partOfSpeech": "adj.", "difficulty": "Advanced", "tags": ["Ethics & Society", "Formal Speech"],
         "englishDefinition": "Unreasonably high, especially of a price or amount.", "tamilDefinition": "அதிகப்படியான அல்லது அளவுக்கு மீறிய.",
         "literaryContext": {"english": "The greedy landlord demanded exorbitant rents from impoverished tenant farmers.", "tamil": "பேராசை பிடித்த நிலக்கிழார் ஏழை குத்தகை விவசாயிகளிடமிருந்து அளவுக்கு மீறிய வாடகையைக் கோரினார்.", "sourceNote": "Social Fiction"},
         "formalSpeechContext": {"english": "Regulatory authorities acted to curb exorbitant interest rates charged by predatory lenders.", "tamil": "கொடூரமான கடன் வழங்குநர்கள் விதிக்கும் அதிகப்படியான வட்டி விகிதங்களைக் கட்டுப்படுத்த ஒழுங்குமுறை அதிகாரிகள் நடவடிக்கை எடுத்தனர்.", "sourceNote": "Consumer Protection Hearing"},
         "synonyms": ["excessive", "extravagant", "unreasonable", "inflated"], "antonyms": ["reasonable", "moderate", "inexpensive", "fair"]},
        {"id": "exploitation", "word": "Exploitation", "partOfSpeech": "noun", "difficulty": "Advanced", "tags": ["Politics", "Ethics & Society"],
         "englishDefinition": "The action or fact of treating someone unfairly in order to benefit from their work.", "tamilDefinition": "சுரண்டல் அல்லது தவறாகப் பயன்படுத்துதல்.",
         "literaryContext": {"english": "Nineteenth-century novels frequently critiqued the industrial exploitation of child labor.", "tamil": "பத்தொன்பதாம் நூற்றாண்டு நாவல்கள் குழந்தை தொழிலாளர்களின் தொழில்மயச் சுரண்டலைக் கடுமையாக விமர்சித்தன.", "sourceNote": "Social History"},
         "formalSpeechContext": {"english": "Labor laws strictly prohibit the unfair exploitation of vulnerable workers.", "tamil": "தொழிலாளர் சட்டங்கள் பாதிக்கப்படக்கூடிய தொழிலாளர்களை நியாயமற்ற முறையில் சுரண்டுவதை திட்டவட்டமாகத் தடை செய்கின்றன.", "sourceNote": "Labor Rights Symposium"},
         "synonyms": ["abuse", "victimization", "misuse", "manipulation"], "antonyms": ["fairness", "protection", "support", "empowerment"]}
    ]
}

print("Loaded lexicon additions dictionary keys:", list(LEXICON_ADDITIONS.keys()))
